module.exports = {
    GPS_TIMEOUT_SECONDS: parseInt(process.env.GPS_TIMEOUT_SECONDS, 10) || 60,
    GPS_CHECK_INTERVAL_MS: parseInt(process.env.GPS_CHECK_INTERVAL_MS, 10) || 15000,
    GPS_INACTIVITY_AUTO_CLOSE_MINUTES: parseInt(process.env.GPS_INACTIVITY_AUTO_CLOSE_MINUTES, 10) || 120,
    TRIP_AUTO_CLOSE_CRON_SCHEDULE: process.env.TRIP_AUTO_CLOSE_CRON_SCHEDULE || '*/5 * * * *',
    DEFAULT_GEOFENCE_RADIUS_METERS: parseInt(process.env.GEOFENCE_RADIUS_METERS, 10) || 100,
    APPROACHING_GEOFENCE_RADIUS_METERS: parseInt(process.env.APPROACHING_GEOFENCE_RADIUS_METERS, 10) || 500,
    GEOFENCE_MAX_SPEED_KMH: parseInt(process.env.GEOFENCE_MAX_SPEED_KMH, 10) || 120,
    OVERSPEED_LIMIT_KMH: parseInt(process.env.TRANSPORT_OVERSPEED_LIMIT_KMH, 10) || 50,
    ROUTE_DEVIATION_THRESHOLD_METERS: parseInt(process.env.ROUTE_DEVIATION_THRESHOLD_METERS, 10) || 600,
    STOP_DWELL_SECONDS: parseInt(process.env.TRANSPORT_STOP_DWELL_SECONDS, 10) || 60,
    AUTO_CLOSE_REASONS: Object.freeze({
        DRIVER_FORGOT_TO_END: 'DRIVER_FORGOT_TO_END',
        NO_GPS_ACTIVITY: 'NO_GPS_ACTIVITY',
        MIDNIGHT_AUTO_CLOSE: 'MIDNIGHT_AUTO_CLOSE',
        ALL_STUDENTS_DROPPED: 'ALL_STUDENTS_DROPPED',
        ADMIN_FORCE_CLOSE: 'ADMIN_FORCE_CLOSE'
    })
};