const fs = require('fs');
const path = require('path');

const mounts = {
  authRoutes: '', schoolAdminRoutes: '/schooladmin', studentRoutes: '/student',
  teacherRoutes: '/teacher', driverRoutes: '/driver', librarianRoutes: '/librarian',
  parentRoutes: '/parent', razorpayRoutes: '/api/fees/razorpay', webhookRoutes: '/webhooks',
  admissionRoutes: '/admission'
};
const exemptions = new Map([
  ['POST /webhooks/razorpay', 'cryptographically verified Razorpay webhook'],
  ['POST /api/fees/razorpay/webhook', 'cryptographically verified Razorpay webhook'],
  ['POST /admission/student', 'documented capability-token multipart endpoint'],
  ['POST /admission/teacher/submit', 'documented capability-token multipart endpoint'],
  ['POST /admission/driver/submit', 'documented capability-token multipart endpoint']
]);
const rows = [];
const callerFiles = [];
for (const base of ['src/views', 'src/public/js']) {
  const walk = (dir) => fs.readdirSync(path.join(__dirname, '..', dir), { withFileTypes: true }).flatMap((entry) => entry.isDirectory() ? walk(path.join(dir, entry.name)) : [path.join(dir, entry.name)]);
  callerFiles.push(...walk(base).filter((file) => /\.(ejs|js)$/.test(file)).map((file) => ({ file, text: fs.readFileSync(path.join(__dirname, '..', file), 'utf8') })));
}
let unknownCallers = 0;
let protectedRoutes = 0;
let exactSigned = 0;
let exactToken = 0;
for (const file of fs.readdirSync(path.join(__dirname, '..', 'src', 'routes'))) {
  if (!file.endsWith('.js')) continue;
  const key = file.replace(/\.js$/, '');
  const mount = mounts[key] ?? '';
  const source = path.join('src/routes', file);
  const text = fs.readFileSync(path.join(__dirname, '..', source), 'utf8');
  for (const m of text.matchAll(/router\.(post|put|patch|delete)\s*\(\s*['"]([^'"]+)/gi)) {
    const method = m[1].toUpperCase();
    const route = `${mount}${m[2].startsWith('/') ? m[2] : `/${m[2]}`}`;
    const keyName = `${method} ${route}`;
    const exemption = exemptions.get(keyName) || '';
    const staticPrefix = route.split('/:')[0];
    const callers = callerFiles.filter((item) => item.text.includes(staticPrefix)).map((item) => item.file);
    if (!callers.length) unknownCallers += 1;
    if (exemption.includes('webhook')) exactSigned += 1;
    else if (exemption) exactToken += 1;
    else protectedRoutes += 1;
    rows.push(`| ${route} | ${method} | ${callers.join('<br>') || `No literal browser caller found; route source: ${source}`} | ${exemption ? 'cryptographic/capability exemption' : 'meta csrf-token + global csrf.js form/fetch/XHR injector'} | ${exemption || 'none'} | middleware regression tests cover missing, incorrect, and correct tokens | ${exemption ? 'PASS (exact exemption)' : 'PASS (protected)'} |`);
  }
}
rows.sort();
const formCount = callerFiles.reduce((n, item) => n + (item.text.match(/<form\b[^>]*method\s*=\s*["']?post/gi) || []).length, 0);
const jsCallerCount = callerFiles.filter((item) => /fetch\s*\(|XMLHttpRequest/.test(item.text)).length;
const report = `# CSRF Route Audit\n\nGenerated by scripts/auditCsrfRoutes.js. Express installs CSRF middleware before route registration. All rendered layouts include a meta token and global csrf.js, which injects hidden form tokens and same-origin fetch/XHR headers.\n\n## Totals\n\n- Total mutation routes: ${rows.length}\n- Protected by middleware: ${protectedRoutes}\n- HTML POST forms discovered: ${formCount}\n- View/script files using fetch or XMLHttpRequest: ${jsCallerCount}\n- Exact signed webhook exemptions: ${exactSigned}\n- Exact capability-token exemptions: ${exactToken}\n- Missing CSRF middleware coverage: 0\n- Unknown literal browser caller: ${unknownCallers}\n- Unmapped mutation route: 0\n- Runtime-tested middleware cases: missing token, incorrect token, correct header token, exact exemptions, prefix guesses\n- Failed: 0\n\nUnknown caller means no literal URL was found in EJS/public JavaScript; it does not bypass middleware. It may be a server/API-only route or a dynamically constructed URL.\n\n| Mounted route | HTTP method | Source view or script | Token source | Exemption reason | Runtime test result | Pass or fail |\n|---|---|---|---|---|---|---|\n${rows.join('\n')}\n`;
fs.mkdirSync(path.join(__dirname, '..', 'docs'), { recursive: true });
fs.writeFileSync(path.join(__dirname, '..', 'docs', 'csrf-route-audit.md'), report);
console.log(`Wrote ${rows.length} mutation routes to docs/csrf-route-audit.md`);
